"""Catalog of OpenRouter models with pricing data for cost estimation.

Prices are per 1M tokens (input/output) in USD.
AUTO-GENERATED from OpenRouter on 2026-05-29 by scripts/check_models.py --regen-catalog.
Re-run that script to refresh. Manual edits will be overwritten.
"""

# Assumed tokens for a typical query cost estimate:
# 1500 input tokens (prompt + context) + 500 output tokens per model
_TYPICAL_INPUT_TOKENS = 1500
_TYPICAL_OUTPUT_TOKENS = 500

CATALOG: list[dict] = [
    # --- Anthropic ---
    {
        "id": "anthropic/claude-opus-4.6-fast",
        "name": "Anthropic: Claude Opus 4.6 (Fast)",
        "provider": "Anthropic",
        "input_price_per_1m": 30.0,
        "output_price_per_1m": 150.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.7-fast",
        "name": "Anthropic: Claude Opus 4.7 (Fast)",
        "provider": "Anthropic",
        "input_price_per_1m": 30.0,
        "output_price_per_1m": 150.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4",
        "name": "Anthropic: Claude Opus 4",
        "provider": "Anthropic",
        "input_price_per_1m": 15.0,
        "output_price_per_1m": 75.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.1",
        "name": "Anthropic: Claude Opus 4.1",
        "provider": "Anthropic",
        "input_price_per_1m": 15.0,
        "output_price_per_1m": 75.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.8-fast",
        "name": "Anthropic: Claude Opus 4.8 (Fast)",
        "provider": "Anthropic",
        "input_price_per_1m": 10.0,
        "output_price_per_1m": 50.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.5",
        "name": "Anthropic: Claude Opus 4.5",
        "provider": "Anthropic",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 25.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.6",
        "name": "Anthropic: Claude Opus 4.6",
        "provider": "Anthropic",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 25.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.7",
        "name": "Anthropic: Claude Opus 4.7",
        "provider": "Anthropic",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 25.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-opus-4.8",
        "name": "Anthropic: Claude Opus 4.8",
        "provider": "Anthropic",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 25.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-sonnet-4",
        "name": "Anthropic: Claude Sonnet 4",
        "provider": "Anthropic",
        "input_price_per_1m": 3.0,
        "output_price_per_1m": 15.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-sonnet-4.5",
        "name": "Anthropic: Claude Sonnet 4.5",
        "provider": "Anthropic",
        "input_price_per_1m": 3.0,
        "output_price_per_1m": 15.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-sonnet-4.6",
        "name": "Anthropic: Claude Sonnet 4.6",
        "provider": "Anthropic",
        "input_price_per_1m": 3.0,
        "output_price_per_1m": 15.0,
        "context_window": 1000000,
        "tier": "premium",
    },
    {
        "id": "anthropic/claude-haiku-4.5",
        "name": "Anthropic: Claude Haiku 4.5",
        "provider": "Anthropic",
        "input_price_per_1m": 1.0,
        "output_price_per_1m": 5.0,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "anthropic/claude-3.5-haiku",
        "name": "Anthropic: Claude 3.5 Haiku",
        "provider": "Anthropic",
        "input_price_per_1m": 0.8,
        "output_price_per_1m": 4.0,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "anthropic/claude-3-haiku",
        "name": "Anthropic: Claude 3 Haiku",
        "provider": "Anthropic",
        "input_price_per_1m": 0.25,
        "output_price_per_1m": 1.25,
        "context_window": 200000,
        "tier": "cheap",
    },
    # --- DeepSeek ---
    {
        "id": "deepseek/deepseek-r1",
        "name": "DeepSeek: R1",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.7,
        "output_price_per_1m": 2.5,
        "context_window": 163840,
        "tier": "mid",
    },
    {
        "id": "deepseek/deepseek-r1-0528",
        "name": "DeepSeek: R1 0528",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.5,
        "output_price_per_1m": 2.15,
        "context_window": 163840,
        "tier": "mid",
    },
    {
        "id": "deepseek/deepseek-v3.1-terminus",
        "name": "DeepSeek: DeepSeek V3.1 Terminus",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.27,
        "output_price_per_1m": 0.95,
        "context_window": 163840,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-chat",
        "name": "DeepSeek: DeepSeek V3",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.2288,
        "output_price_per_1m": 0.9144,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-v4-pro",
        "name": "DeepSeek: DeepSeek V4 Pro",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.435,
        "output_price_per_1m": 0.87,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-r1-distill-llama-70b",
        "name": "DeepSeek: R1 Distill Llama 70B",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.7,
        "output_price_per_1m": 0.8,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-chat-v3.1",
        "name": "DeepSeek: DeepSeek V3.1",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.21,
        "output_price_per_1m": 0.79,
        "context_window": 163840,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-chat-v3-0324",
        "name": "DeepSeek: DeepSeek V3 0324",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.2,
        "output_price_per_1m": 0.77,
        "context_window": 163840,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-v3.2-exp",
        "name": "DeepSeek: DeepSeek V3.2 Exp",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.27,
        "output_price_per_1m": 0.41,
        "context_window": 163840,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-v3.2",
        "name": "DeepSeek: DeepSeek V3.2",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.252,
        "output_price_per_1m": 0.378,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-r1-distill-qwen-32b",
        "name": "DeepSeek: R1 Distill Qwen 32B",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.29,
        "output_price_per_1m": 0.29,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "deepseek/deepseek-v4-flash",
        "name": "DeepSeek: DeepSeek V4 Flash",
        "provider": "DeepSeek",
        "input_price_per_1m": 0.0983,
        "output_price_per_1m": 0.1966,
        "context_window": 1048576,
        "tier": "cheap",
    },
    # --- Google ---
    {
        "id": "google/gemini-3-pro-image-preview",
        "name": "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
        "provider": "Google",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 12.0,
        "context_window": 65536,
        "tier": "premium",
    },
    {
        "id": "google/gemini-3.1-pro-preview",
        "name": "Google: Gemini 3.1 Pro Preview",
        "provider": "Google",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 12.0,
        "context_window": 1048576,
        "tier": "premium",
    },
    {
        "id": "google/gemini-3.1-pro-preview-customtools",
        "name": "Google: Gemini 3.1 Pro Preview Custom Tools",
        "provider": "Google",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 12.0,
        "context_window": 1048756,
        "tier": "premium",
    },
    {
        "id": "google/gemini-2.5-pro",
        "name": "Google: Gemini 2.5 Pro",
        "provider": "Google",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 1048576,
        "tier": "premium",
    },
    {
        "id": "google/gemini-2.5-pro-preview",
        "name": "Google: Gemini 2.5 Pro Preview 06-05",
        "provider": "Google",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 1048576,
        "tier": "premium",
    },
    {
        "id": "google/gemini-2.5-pro-preview-05-06",
        "name": "Google: Gemini 2.5 Pro Preview 05-06",
        "provider": "Google",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 1048576,
        "tier": "premium",
    },
    {
        "id": "google/gemini-3.5-flash",
        "name": "Google: Gemini 3.5 Flash",
        "provider": "Google",
        "input_price_per_1m": 1.5,
        "output_price_per_1m": 9.0,
        "context_window": 1048576,
        "tier": "mid",
    },
    {
        "id": "google/gemini-3-flash-preview",
        "name": "Google: Gemini 3 Flash Preview",
        "provider": "Google",
        "input_price_per_1m": 0.5,
        "output_price_per_1m": 3.0,
        "context_window": 1048576,
        "tier": "mid",
    },
    {
        "id": "google/gemini-3.1-flash-image-preview",
        "name": "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
        "provider": "Google",
        "input_price_per_1m": 0.5,
        "output_price_per_1m": 3.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "google/gemini-2.5-flash",
        "name": "Google: Gemini 2.5 Flash",
        "provider": "Google",
        "input_price_per_1m": 0.3,
        "output_price_per_1m": 2.5,
        "context_window": 1048576,
        "tier": "mid",
    },
    {
        "id": "google/gemini-2.5-flash-image",
        "name": "Google: Nano Banana (Gemini 2.5 Flash Image)",
        "provider": "Google",
        "input_price_per_1m": 0.3,
        "output_price_per_1m": 2.5,
        "context_window": 32768,
        "tier": "mid",
    },
    {
        "id": "google/gemini-3.1-flash-lite",
        "name": "Google: Gemini 3.1 Flash Lite",
        "provider": "Google",
        "input_price_per_1m": 0.25,
        "output_price_per_1m": 1.5,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "google/gemini-3.1-flash-lite-preview",
        "name": "Google: Gemini 3.1 Flash Lite Preview",
        "provider": "Google",
        "input_price_per_1m": 0.25,
        "output_price_per_1m": 1.5,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-2-27b-it",
        "name": "Google: Gemma 2 27B",
        "provider": "Google",
        "input_price_per_1m": 0.65,
        "output_price_per_1m": 0.65,
        "context_window": 8192,
        "tier": "cheap",
    },
    {
        "id": "google/gemini-2.0-flash-001",
        "name": "Google: Gemini 2.0 Flash",
        "provider": "Google",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.4,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "google/gemini-2.5-flash-lite",
        "name": "Google: Gemini 2.5 Flash Lite",
        "provider": "Google",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.4,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "google/gemini-2.5-flash-lite-preview-09-2025",
        "name": "Google: Gemini 2.5 Flash Lite Preview 09-2025",
        "provider": "Google",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.4,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-4-31b-it",
        "name": "Google: Gemma 4 31B",
        "provider": "Google",
        "input_price_per_1m": 0.12,
        "output_price_per_1m": 0.37,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-4-26b-a4b-it",
        "name": "Google: Gemma 4 26B A4B ",
        "provider": "Google",
        "input_price_per_1m": 0.06,
        "output_price_per_1m": 0.33,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "google/gemini-2.0-flash-lite-001",
        "name": "Google: Gemini 2.0 Flash Lite",
        "provider": "Google",
        "input_price_per_1m": 0.075,
        "output_price_per_1m": 0.3,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-3-27b-it",
        "name": "Google: Gemma 3 27B",
        "provider": "Google",
        "input_price_per_1m": 0.08,
        "output_price_per_1m": 0.16,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-3-12b-it",
        "name": "Google: Gemma 3 12B",
        "provider": "Google",
        "input_price_per_1m": 0.04,
        "output_price_per_1m": 0.13,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-3n-e4b-it",
        "name": "Google: Gemma 3n 4B",
        "provider": "Google",
        "input_price_per_1m": 0.06,
        "output_price_per_1m": 0.12,
        "context_window": 32768,
        "tier": "cheap",
    },
    {
        "id": "google/gemma-3-4b-it",
        "name": "Google: Gemma 3 4B",
        "provider": "Google",
        "input_price_per_1m": 0.04,
        "output_price_per_1m": 0.08,
        "context_window": 131072,
        "tier": "cheap",
    },
    # --- Meta ---
    {
        "id": "meta-llama/llama-3-70b-instruct",
        "name": "Meta: Llama 3 70B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.51,
        "output_price_per_1m": 0.74,
        "context_window": 8192,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-4-maverick",
        "name": "Meta: Llama 4 Maverick",
        "provider": "Meta",
        "input_price_per_1m": 0.15,
        "output_price_per_1m": 0.6,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3.1-70b-instruct",
        "name": "Meta: Llama 3.1 70B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.4,
        "output_price_per_1m": 0.4,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3.2-3b-instruct",
        "name": "Meta: Llama 3.2 3B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.0509,
        "output_price_per_1m": 0.335,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3.3-70b-instruct",
        "name": "Meta: Llama 3.3 70B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.32,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-4-scout",
        "name": "Meta: Llama 4 Scout",
        "provider": "Meta",
        "input_price_per_1m": 0.08,
        "output_price_per_1m": 0.3,
        "context_window": 10000000,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3.2-11b-vision-instruct",
        "name": "Meta: Llama 3.2 11B Vision Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.245,
        "output_price_per_1m": 0.245,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3.2-1b-instruct",
        "name": "Meta: Llama 3.2 1B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.027,
        "output_price_per_1m": 0.201,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-guard-4-12b",
        "name": "Meta: Llama Guard 4 12B",
        "provider": "Meta",
        "input_price_per_1m": 0.18,
        "output_price_per_1m": 0.18,
        "context_window": 163840,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3.1-8b-instruct",
        "name": "Meta: Llama 3.1 8B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.02,
        "output_price_per_1m": 0.05,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-3-8b-instruct",
        "name": "Meta: Llama 3 8B Instruct",
        "provider": "Meta",
        "input_price_per_1m": 0.04,
        "output_price_per_1m": 0.04,
        "context_window": 8192,
        "tier": "cheap",
    },
    {
        "id": "meta-llama/llama-guard-3-8b",
        "name": "Llama Guard 3 8B",
        "provider": "Meta",
        "input_price_per_1m": 0.484,
        "output_price_per_1m": 0.03,
        "context_window": 131072,
        "tier": "cheap",
    },
    # --- Mistral ---
    {
        "id": "mistralai/mistral-medium-3-5",
        "name": "Mistral: Mistral Medium 3.5",
        "provider": "Mistral",
        "input_price_per_1m": 1.5,
        "output_price_per_1m": 7.5,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "mistralai/mistral-large",
        "name": "Mistral Large",
        "provider": "Mistral",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 6.0,
        "context_window": 128000,
        "tier": "mid",
    },
    {
        "id": "mistralai/mistral-large-2407",
        "name": "Mistral Large 2407",
        "provider": "Mistral",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 6.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "mistralai/mistral-large-2411",
        "name": "Mistral Large 2411",
        "provider": "Mistral",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 6.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "mistralai/mixtral-8x22b-instruct",
        "name": "Mistral: Mixtral 8x22B Instruct",
        "provider": "Mistral",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 6.0,
        "context_window": 65536,
        "tier": "mid",
    },
    {
        "id": "mistralai/pixtral-large-2411",
        "name": "Mistral: Pixtral Large 2411",
        "provider": "Mistral",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 6.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "mistralai/devstral-2512",
        "name": "Mistral: Devstral 2 2512",
        "provider": "Mistral",
        "input_price_per_1m": 0.4,
        "output_price_per_1m": 2.0,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "mistralai/devstral-medium",
        "name": "Mistral: Devstral Medium",
        "provider": "Mistral",
        "input_price_per_1m": 0.4,
        "output_price_per_1m": 2.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "mistralai/mistral-medium-3",
        "name": "Mistral: Mistral Medium 3",
        "provider": "Mistral",
        "input_price_per_1m": 0.4,
        "output_price_per_1m": 2.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "mistralai/mistral-medium-3.1",
        "name": "Mistral: Mistral Medium 3.1",
        "provider": "Mistral",
        "input_price_per_1m": 0.4,
        "output_price_per_1m": 2.0,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "mistralai/mistral-large-2512",
        "name": "Mistral: Mistral Large 3 2512",
        "provider": "Mistral",
        "input_price_per_1m": 0.5,
        "output_price_per_1m": 1.5,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "mistralai/codestral-2508",
        "name": "Mistral: Codestral 2508",
        "provider": "Mistral",
        "input_price_per_1m": 0.3,
        "output_price_per_1m": 0.9,
        "context_window": 256000,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-saba",
        "name": "Mistral: Saba",
        "provider": "Mistral",
        "input_price_per_1m": 0.2,
        "output_price_per_1m": 0.6,
        "context_window": 32768,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-small-2603",
        "name": "Mistral: Mistral Small 4",
        "provider": "Mistral",
        "input_price_per_1m": 0.15,
        "output_price_per_1m": 0.6,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-small-3.1-24b-instruct",
        "name": "Mistral: Mistral Small 3.1 24B",
        "provider": "Mistral",
        "input_price_per_1m": 0.351,
        "output_price_per_1m": 0.555,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "mistralai/devstral-small",
        "name": "Mistral: Devstral Small 1.1",
        "provider": "Mistral",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.3,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "mistralai/voxtral-small-24b-2507",
        "name": "Mistral: Voxtral Small 24B 2507",
        "provider": "Mistral",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.3,
        "context_window": 32000,
        "tier": "cheap",
    },
    {
        "id": "mistralai/ministral-14b-2512",
        "name": "Mistral: Ministral 3 14B 2512",
        "provider": "Mistral",
        "input_price_per_1m": 0.2,
        "output_price_per_1m": 0.2,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-small-3.2-24b-instruct",
        "name": "Mistral: Mistral Small 3.2 24B",
        "provider": "Mistral",
        "input_price_per_1m": 0.075,
        "output_price_per_1m": 0.2,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-7b-instruct-v0.1",
        "name": "Mistral: Mistral 7B Instruct v0.1",
        "provider": "Mistral",
        "input_price_per_1m": 0.11,
        "output_price_per_1m": 0.19,
        "context_window": 4096,
        "tier": "cheap",
    },
    {
        "id": "mistralai/ministral-8b-2512",
        "name": "Mistral: Ministral 3 8B 2512",
        "provider": "Mistral",
        "input_price_per_1m": 0.15,
        "output_price_per_1m": 0.15,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "mistralai/ministral-3b-2512",
        "name": "Mistral: Ministral 3 3B 2512",
        "provider": "Mistral",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.1,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-small-24b-instruct-2501",
        "name": "Mistral: Mistral Small 3",
        "provider": "Mistral",
        "input_price_per_1m": 0.05,
        "output_price_per_1m": 0.08,
        "context_window": 32768,
        "tier": "cheap",
    },
    {
        "id": "mistralai/mistral-nemo",
        "name": "Mistral: Mistral Nemo",
        "provider": "Mistral",
        "input_price_per_1m": 0.02,
        "output_price_per_1m": 0.03,
        "context_window": 131072,
        "tier": "cheap",
    },
    # --- OpenAI ---
    {
        "id": "openai/o1-pro",
        "name": "OpenAI: o1-pro",
        "provider": "OpenAI",
        "input_price_per_1m": 150.0,
        "output_price_per_1m": 600.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.4-pro",
        "name": "OpenAI: GPT-5.4 Pro",
        "provider": "OpenAI",
        "input_price_per_1m": 30.0,
        "output_price_per_1m": 180.0,
        "context_window": 1050000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.5-pro",
        "name": "OpenAI: GPT-5.5 Pro",
        "provider": "OpenAI",
        "input_price_per_1m": 30.0,
        "output_price_per_1m": 180.0,
        "context_window": 1050000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.2-pro",
        "name": "OpenAI: GPT-5.2 Pro",
        "provider": "OpenAI",
        "input_price_per_1m": 21.0,
        "output_price_per_1m": 168.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5-pro",
        "name": "OpenAI: GPT-5 Pro",
        "provider": "OpenAI",
        "input_price_per_1m": 15.0,
        "output_price_per_1m": 120.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/o3-pro",
        "name": "OpenAI: o3 Pro",
        "provider": "OpenAI",
        "input_price_per_1m": 20.0,
        "output_price_per_1m": 80.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4",
        "name": "OpenAI: GPT-4",
        "provider": "OpenAI",
        "input_price_per_1m": 30.0,
        "output_price_per_1m": 60.0,
        "context_window": 8191,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4-0314",
        "name": "OpenAI: GPT-4 (older v0314)",
        "provider": "OpenAI",
        "input_price_per_1m": 30.0,
        "output_price_per_1m": 60.0,
        "context_window": 8191,
        "tier": "premium",
    },
    {
        "id": "openai/o1",
        "name": "OpenAI: o1",
        "provider": "OpenAI",
        "input_price_per_1m": 15.0,
        "output_price_per_1m": 60.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "openai/o3-deep-research",
        "name": "OpenAI: o3 Deep Research",
        "provider": "OpenAI",
        "input_price_per_1m": 10.0,
        "output_price_per_1m": 40.0,
        "context_window": 200000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4-1106-preview",
        "name": "OpenAI: GPT-4 Turbo (older v1106)",
        "provider": "OpenAI",
        "input_price_per_1m": 10.0,
        "output_price_per_1m": 30.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4-turbo",
        "name": "OpenAI: GPT-4 Turbo",
        "provider": "OpenAI",
        "input_price_per_1m": 10.0,
        "output_price_per_1m": 30.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4-turbo-preview",
        "name": "OpenAI: GPT-4 Turbo Preview",
        "provider": "OpenAI",
        "input_price_per_1m": 10.0,
        "output_price_per_1m": 30.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.5",
        "name": "OpenAI: GPT-5.5",
        "provider": "OpenAI",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 30.0,
        "context_window": 1050000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-chat-latest",
        "name": "OpenAI: GPT Chat Latest",
        "provider": "OpenAI",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 30.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4o-2024-05-13",
        "name": "OpenAI: GPT-4o (2024-05-13)",
        "provider": "OpenAI",
        "input_price_per_1m": 5.0,
        "output_price_per_1m": 15.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.4",
        "name": "OpenAI: GPT-5.4",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 15.0,
        "context_window": 1050000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.4-image-2",
        "name": "OpenAI: GPT-5.4 Image 2",
        "provider": "OpenAI",
        "input_price_per_1m": 8.0,
        "output_price_per_1m": 15.0,
        "context_window": 272000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.2",
        "name": "OpenAI: GPT-5.2",
        "provider": "OpenAI",
        "input_price_per_1m": 1.75,
        "output_price_per_1m": 14.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.2-chat",
        "name": "OpenAI: GPT-5.2 Chat",
        "provider": "OpenAI",
        "input_price_per_1m": 1.75,
        "output_price_per_1m": 14.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.2-codex",
        "name": "OpenAI: GPT-5.2-Codex",
        "provider": "OpenAI",
        "input_price_per_1m": 1.75,
        "output_price_per_1m": 14.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.3-chat",
        "name": "OpenAI: GPT-5.3 Chat",
        "provider": "OpenAI",
        "input_price_per_1m": 1.75,
        "output_price_per_1m": 14.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.3-codex",
        "name": "OpenAI: GPT-5.3-Codex",
        "provider": "OpenAI",
        "input_price_per_1m": 1.75,
        "output_price_per_1m": 14.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4o",
        "name": "OpenAI: GPT-4o",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4o-2024-08-06",
        "name": "OpenAI: GPT-4o (2024-08-06)",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4o-2024-11-20",
        "name": "OpenAI: GPT-4o (2024-11-20)",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4o-audio-preview",
        "name": "OpenAI: GPT-4o Audio",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4o-search-preview",
        "name": "OpenAI: GPT-4o Search Preview",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5",
        "name": "OpenAI: GPT-5",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5-chat",
        "name": "OpenAI: GPT-5 Chat",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5-codex",
        "name": "OpenAI: GPT-5 Codex",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5-image",
        "name": "OpenAI: GPT-5 Image",
        "provider": "OpenAI",
        "input_price_per_1m": 10.0,
        "output_price_per_1m": 10.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.1",
        "name": "OpenAI: GPT-5.1",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.1-chat",
        "name": "OpenAI: GPT-5.1 Chat",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.1-codex",
        "name": "OpenAI: GPT-5.1-Codex",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-5.1-codex-max",
        "name": "OpenAI: GPT-5.1-Codex-Max",
        "provider": "OpenAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 10.0,
        "context_window": 400000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-audio",
        "name": "OpenAI: GPT Audio",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 10.0,
        "context_window": 128000,
        "tier": "premium",
    },
    {
        "id": "openai/gpt-4.1",
        "name": "OpenAI: GPT-4.1",
        "provider": "OpenAI",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 8.0,
        "context_window": 1047576,
        "tier": "mid",
    },
    {
        "id": "openai/o3",
        "name": "OpenAI: o3",
        "provider": "OpenAI",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 8.0,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "openai/o4-mini-deep-research",
        "name": "OpenAI: o4 Mini Deep Research",
        "provider": "OpenAI",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 8.0,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-5.4-mini",
        "name": "OpenAI: GPT-5.4 Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 0.75,
        "output_price_per_1m": 4.5,
        "context_window": 400000,
        "tier": "mid",
    },
    {
        "id": "openai/o3-mini",
        "name": "OpenAI: o3 Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 1.1,
        "output_price_per_1m": 4.4,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "openai/o3-mini-high",
        "name": "OpenAI: o3 Mini High",
        "provider": "OpenAI",
        "input_price_per_1m": 1.1,
        "output_price_per_1m": 4.4,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "openai/o4-mini",
        "name": "OpenAI: o4 Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 1.1,
        "output_price_per_1m": 4.4,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "openai/o4-mini-high",
        "name": "OpenAI: o4 Mini High",
        "provider": "OpenAI",
        "input_price_per_1m": 1.1,
        "output_price_per_1m": 4.4,
        "context_window": 200000,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-3.5-turbo-16k",
        "name": "OpenAI: GPT-3.5 Turbo 16k",
        "provider": "OpenAI",
        "input_price_per_1m": 3.0,
        "output_price_per_1m": 4.0,
        "context_window": 16385,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-audio-mini",
        "name": "OpenAI: GPT Audio Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 0.6,
        "output_price_per_1m": 2.4,
        "context_window": 128000,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-3.5-turbo-0613",
        "name": "OpenAI: GPT-3.5 Turbo (older v0613)",
        "provider": "OpenAI",
        "input_price_per_1m": 1.0,
        "output_price_per_1m": 2.0,
        "context_window": 4095,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-3.5-turbo-instruct",
        "name": "OpenAI: GPT-3.5 Turbo Instruct",
        "provider": "OpenAI",
        "input_price_per_1m": 1.5,
        "output_price_per_1m": 2.0,
        "context_window": 4095,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-5-image-mini",
        "name": "OpenAI: GPT-5 Image Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 2.5,
        "output_price_per_1m": 2.0,
        "context_window": 400000,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-5-mini",
        "name": "OpenAI: GPT-5 Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 0.25,
        "output_price_per_1m": 2.0,
        "context_window": 400000,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-5.1-codex-mini",
        "name": "OpenAI: GPT-5.1-Codex-Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 0.25,
        "output_price_per_1m": 2.0,
        "context_window": 400000,
        "tier": "mid",
    },
    {
        "id": "openai/gpt-4.1-mini",
        "name": "OpenAI: GPT-4.1 Mini",
        "provider": "OpenAI",
        "input_price_per_1m": 0.4,
        "output_price_per_1m": 1.6,
        "context_window": 1047576,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-3.5-turbo",
        "name": "OpenAI: GPT-3.5 Turbo",
        "provider": "OpenAI",
        "input_price_per_1m": 0.5,
        "output_price_per_1m": 1.5,
        "context_window": 16385,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-5.4-nano",
        "name": "OpenAI: GPT-5.4 Nano",
        "provider": "OpenAI",
        "input_price_per_1m": 0.2,
        "output_price_per_1m": 1.25,
        "context_window": 400000,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-4o-mini",
        "name": "OpenAI: GPT-4o-mini",
        "provider": "OpenAI",
        "input_price_per_1m": 0.15,
        "output_price_per_1m": 0.6,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-4o-mini-2024-07-18",
        "name": "OpenAI: GPT-4o-mini (2024-07-18)",
        "provider": "OpenAI",
        "input_price_per_1m": 0.15,
        "output_price_per_1m": 0.6,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-4o-mini-search-preview",
        "name": "OpenAI: GPT-4o-mini Search Preview",
        "provider": "OpenAI",
        "input_price_per_1m": 0.15,
        "output_price_per_1m": 0.6,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-4.1-nano",
        "name": "OpenAI: GPT-4.1 Nano",
        "provider": "OpenAI",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.4,
        "context_window": 1047576,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-5-nano",
        "name": "OpenAI: GPT-5 Nano",
        "provider": "OpenAI",
        "input_price_per_1m": 0.05,
        "output_price_per_1m": 0.4,
        "context_window": 400000,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-oss-safeguard-20b",
        "name": "OpenAI: gpt-oss-safeguard-20b",
        "provider": "OpenAI",
        "input_price_per_1m": 0.075,
        "output_price_per_1m": 0.3,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-oss-120b",
        "name": "OpenAI: gpt-oss-120b",
        "provider": "OpenAI",
        "input_price_per_1m": 0.039,
        "output_price_per_1m": 0.18,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "openai/gpt-oss-20b",
        "name": "OpenAI: gpt-oss-20b",
        "provider": "OpenAI",
        "input_price_per_1m": 0.03,
        "output_price_per_1m": 0.14,
        "context_window": 131072,
        "tier": "cheap",
    },
    # --- Qwen ---
    {
        "id": "qwen/qwen3.6-max-preview",
        "name": "Qwen: Qwen3.6 Max Preview",
        "provider": "Qwen",
        "input_price_per_1m": 1.04,
        "output_price_per_1m": 6.24,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3-max",
        "name": "Qwen: Qwen3 Max",
        "provider": "Qwen",
        "input_price_per_1m": 0.78,
        "output_price_per_1m": 3.9,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3-max-thinking",
        "name": "Qwen: Qwen3 Max Thinking",
        "provider": "Qwen",
        "input_price_per_1m": 0.78,
        "output_price_per_1m": 3.9,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3.7-max",
        "name": "Qwen: Qwen3.7 Max",
        "provider": "Qwen",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 3.75,
        "context_window": 1000000,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3-coder-plus",
        "name": "Qwen: Qwen3 Coder Plus",
        "provider": "Qwen",
        "input_price_per_1m": 0.65,
        "output_price_per_1m": 3.25,
        "context_window": 1000000,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3.6-27b",
        "name": "Qwen: Qwen3.6 27B",
        "provider": "Qwen",
        "input_price_per_1m": 0.29,
        "output_price_per_1m": 3.2,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3-vl-235b-a22b-thinking",
        "name": "Qwen: Qwen3 VL 235B A22B Thinking",
        "provider": "Qwen",
        "input_price_per_1m": 0.26,
        "output_price_per_1m": 2.6,
        "context_window": 131072,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3.5-397b-a17b",
        "name": "Qwen: Qwen3.5 397B A17B",
        "provider": "Qwen",
        "input_price_per_1m": 0.39,
        "output_price_per_1m": 2.34,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3.5-122b-a10b",
        "name": "Qwen: Qwen3.5-122B-A10B",
        "provider": "Qwen",
        "input_price_per_1m": 0.26,
        "output_price_per_1m": 2.08,
        "context_window": 262144,
        "tier": "mid",
    },
    {
        "id": "qwen/qwen3.6-plus",
        "name": "Qwen: Qwen3.6 Plus",
        "provider": "Qwen",
        "input_price_per_1m": 0.325,
        "output_price_per_1m": 1.95,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-235b-a22b",
        "name": "Qwen: Qwen3 235B A22B",
        "provider": "Qwen",
        "input_price_per_1m": 0.455,
        "output_price_per_1m": 1.82,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-coder",
        "name": "Qwen: Qwen3 Coder 480B A35B",
        "provider": "Qwen",
        "input_price_per_1m": 0.22,
        "output_price_per_1m": 1.8,
        "context_window": 1048576,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.5-plus-20260420",
        "name": "Qwen: Qwen3.5 Plus 2026-04-20",
        "provider": "Qwen",
        "input_price_per_1m": 0.3,
        "output_price_per_1m": 1.8,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-vl-30b-a3b-thinking",
        "name": "Qwen: Qwen3 VL 30B A3B Thinking",
        "provider": "Qwen",
        "input_price_per_1m": 0.13,
        "output_price_per_1m": 1.56,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.5-27b",
        "name": "Qwen: Qwen3.5-27B",
        "provider": "Qwen",
        "input_price_per_1m": 0.195,
        "output_price_per_1m": 1.56,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.5-plus-02-15",
        "name": "Qwen: Qwen3.5 Plus 2026-02-15",
        "provider": "Qwen",
        "input_price_per_1m": 0.26,
        "output_price_per_1m": 1.56,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-235b-a22b-thinking-2507",
        "name": "Qwen: Qwen3 235B A22B Thinking 2507",
        "provider": "Qwen",
        "input_price_per_1m": 0.1495,
        "output_price_per_1m": 1.495,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-vl-8b-thinking",
        "name": "Qwen: Qwen3 VL 8B Thinking",
        "provider": "Qwen",
        "input_price_per_1m": 0.117,
        "output_price_per_1m": 1.365,
        "context_window": 256000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.6-flash",
        "name": "Qwen: Qwen3.6 Flash",
        "provider": "Qwen",
        "input_price_per_1m": 0.1875,
        "output_price_per_1m": 1.125,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-next-80b-a3b-instruct",
        "name": "Qwen: Qwen3 Next 80B A3B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.09,
        "output_price_per_1m": 1.1,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen-2.5-coder-32b-instruct",
        "name": "Qwen2.5 Coder 32B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.66,
        "output_price_per_1m": 1.0,
        "context_window": 128000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.5-35b-a3b",
        "name": "Qwen: Qwen3.5-35B-A3B",
        "provider": "Qwen",
        "input_price_per_1m": 0.139,
        "output_price_per_1m": 1.0,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.6-35b-a3b",
        "name": "Qwen: Qwen3.6 35B A3B",
        "provider": "Qwen",
        "input_price_per_1m": 0.14,
        "output_price_per_1m": 1.0,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-coder-flash",
        "name": "Qwen: Qwen3 Coder Flash",
        "provider": "Qwen",
        "input_price_per_1m": 0.195,
        "output_price_per_1m": 0.975,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-vl-235b-a22b-instruct",
        "name": "Qwen: Qwen3 VL 235B A22B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.2,
        "output_price_per_1m": 0.88,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-coder-next",
        "name": "Qwen: Qwen3 Coder Next",
        "provider": "Qwen",
        "input_price_per_1m": 0.11,
        "output_price_per_1m": 0.8,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen-plus",
        "name": "Qwen: Qwen-Plus",
        "provider": "Qwen",
        "input_price_per_1m": 0.26,
        "output_price_per_1m": 0.78,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen-plus-2025-07-28",
        "name": "Qwen: Qwen Plus 0728",
        "provider": "Qwen",
        "input_price_per_1m": 0.26,
        "output_price_per_1m": 0.78,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen-plus-2025-07-28:thinking",
        "name": "Qwen: Qwen Plus 0728 (thinking)",
        "provider": "Qwen",
        "input_price_per_1m": 0.26,
        "output_price_per_1m": 0.78,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-next-80b-a3b-thinking",
        "name": "Qwen: Qwen3 Next 80B A3B Thinking",
        "provider": "Qwen",
        "input_price_per_1m": 0.0975,
        "output_price_per_1m": 0.78,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen2.5-vl-72b-instruct",
        "name": "Qwen: Qwen2.5 VL 72B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.25,
        "output_price_per_1m": 0.75,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-vl-30b-a3b-instruct",
        "name": "Qwen: Qwen3 VL 30B A3B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.13,
        "output_price_per_1m": 0.52,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-vl-8b-instruct",
        "name": "Qwen: Qwen3 VL 8B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.08,
        "output_price_per_1m": 0.5,
        "context_window": 256000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-30b-a3b",
        "name": "Qwen: Qwen3 30B A3B",
        "provider": "Qwen",
        "input_price_per_1m": 0.09,
        "output_price_per_1m": 0.45,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-vl-32b-instruct",
        "name": "Qwen: Qwen3 VL 32B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.104,
        "output_price_per_1m": 0.416,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen-2.5-72b-instruct",
        "name": "Qwen2.5 72B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.36,
        "output_price_per_1m": 0.4,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-30b-a3b-thinking-2507",
        "name": "Qwen: Qwen3 30B A3B Thinking 2507",
        "provider": "Qwen",
        "input_price_per_1m": 0.08,
        "output_price_per_1m": 0.4,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-8b",
        "name": "Qwen: Qwen3 8B",
        "provider": "Qwen",
        "input_price_per_1m": 0.05,
        "output_price_per_1m": 0.4,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-30b-a3b-instruct-2507",
        "name": "Qwen: Qwen3 30B A3B Instruct 2507",
        "provider": "Qwen",
        "input_price_per_1m": 0.09,
        "output_price_per_1m": 0.3,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-32b",
        "name": "Qwen: Qwen3 32B",
        "provider": "Qwen",
        "input_price_per_1m": 0.08,
        "output_price_per_1m": 0.28,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-coder-30b-a3b-instruct",
        "name": "Qwen: Qwen3 Coder 30B A3B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.07,
        "output_price_per_1m": 0.27,
        "context_window": 160000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.5-flash-02-23",
        "name": "Qwen: Qwen3.5-Flash",
        "provider": "Qwen",
        "input_price_per_1m": 0.065,
        "output_price_per_1m": 0.26,
        "context_window": 1000000,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-14b",
        "name": "Qwen: Qwen3 14B",
        "provider": "Qwen",
        "input_price_per_1m": 0.1,
        "output_price_per_1m": 0.24,
        "context_window": 131702,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3.5-9b",
        "name": "Qwen: Qwen3.5-9B",
        "provider": "Qwen",
        "input_price_per_1m": 0.04,
        "output_price_per_1m": 0.15,
        "context_window": 262144,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen-2.5-7b-instruct",
        "name": "Qwen: Qwen2.5 7B Instruct",
        "provider": "Qwen",
        "input_price_per_1m": 0.04,
        "output_price_per_1m": 0.1,
        "context_window": 131072,
        "tier": "cheap",
    },
    {
        "id": "qwen/qwen3-235b-a22b-2507",
        "name": "Qwen: Qwen3 235B A22B Instruct 2507",
        "provider": "Qwen",
        "input_price_per_1m": 0.071,
        "output_price_per_1m": 0.1,
        "context_window": 262144,
        "tier": "cheap",
    },
    # --- xAI ---
    {
        "id": "x-ai/grok-4.20-multi-agent",
        "name": "xAI: Grok 4.20 Multi-Agent",
        "provider": "xAI",
        "input_price_per_1m": 2.0,
        "output_price_per_1m": 6.0,
        "context_window": 2000000,
        "tier": "mid",
    },
    {
        "id": "x-ai/grok-4.20",
        "name": "xAI: Grok 4.20",
        "provider": "xAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 2.5,
        "context_window": 2000000,
        "tier": "mid",
    },
    {
        "id": "x-ai/grok-4.3",
        "name": "xAI: Grok 4.3",
        "provider": "xAI",
        "input_price_per_1m": 1.25,
        "output_price_per_1m": 2.5,
        "context_window": 1000000,
        "tier": "mid",
    },
    {
        "id": "x-ai/grok-build-0.1",
        "name": "xAI: Grok Build 0.1",
        "provider": "xAI",
        "input_price_per_1m": 1.0,
        "output_price_per_1m": 2.0,
        "context_window": 256000,
        "tier": "mid",
    },
]

# Index for O(1) lookup by model id
_CATALOG_INDEX: dict[str, dict] = {m["id"]: m for m in CATALOG}


def get_catalog() -> list[dict]:
    return CATALOG


def get_model(model_id: str) -> dict | None:
    return _CATALOG_INDEX.get(model_id)


def estimate_query_cost(model_ids: list[str]) -> dict:
    """Estimate cost for one full council query (all members + chairman synthesizes).

    Chairman is assumed to be one of the model_ids, so it's already counted.
    Each model processes the full prompt (input) and produces a response (output).
    """
    total_input_cost = 0.0
    total_output_cost = 0.0
    known_models = 0

    for model_id in model_ids:
        model = _CATALOG_INDEX.get(model_id)
        if model is None:
            continue
        known_models += 1
        total_input_cost += model["input_price_per_1m"] * _TYPICAL_INPUT_TOKENS / 1_000_000
        total_output_cost += model["output_price_per_1m"] * _TYPICAL_OUTPUT_TOKENS / 1_000_000

    if known_models > 0:
        avg_input_per_1m = sum(
            _CATALOG_INDEX[m]["input_price_per_1m"]
            for m in model_ids
            if m in _CATALOG_INDEX
        ) / known_models
        avg_output_per_1m = sum(
            _CATALOG_INDEX[m]["output_price_per_1m"]
            for m in model_ids
            if m in _CATALOG_INDEX
        ) / known_models
    else:
        avg_input_per_1m = 0.0
        avg_output_per_1m = 0.0

    return {
        "per_query_usd": round(total_input_cost + total_output_cost, 6),
        "avg_input_per_1m_usd": round(avg_input_per_1m, 4),
        "avg_output_per_1m_usd": round(avg_output_per_1m, 4),
        "known_models": known_models,
        "total_models": len(model_ids),
    }
